// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iknow_api.Data;

#nullable disable

namespace iknow_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211135004_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iknow_api.Models.ActiveSemesters", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("year")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("ActiveSemesters");
                });

            modelBuilder.Entity("iknow_api.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("MicrosoftEmail")
                        .HasColumnType("text");

                    b.Property<string>("Municipality")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ContactInfo");
                });

            modelBuilder.Entity("iknow_api.Models.DependencySubject", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("DependencyId")
                        .HasColumnType("integer");

                    b.HasKey("SubjectId", "DependencyId");

                    b.HasIndex("DependencyId");

                    b.ToTable("DependencySubjects");
                });

            modelBuilder.Entity("iknow_api.Models.Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("iknow_api.Models.EnrolledSemesters", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MajorId")
                        .HasColumnType("integer");

                    b.Property<string>("Node")
                        .HasColumnType("text");

                    b.Property<int>("QuotaType")
                        .HasColumnType("integer");

                    b.Property<string>("StudentComment")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Veryfied")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.HasIndex("UserId");

                    b.ToTable("EnrolledSemesters");
                });

            modelBuilder.Entity("iknow_api.Models.EnrollmentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MajorId")
                        .HasColumnType("integer");

                    b.Property<string>("StudyStatus")
                        .HasColumnType("text");

                    b.Property<string>("StudyType")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("enrollmentYear")
                        .HasColumnType("integer");

                    b.Property<int>("quota")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EnrollmentInfo");
                });

            modelBuilder.Entity("iknow_api.Models.HighSchool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("GPA")
                        .HasColumnType("real");

                    b.Property<int>("HighSchoolType")
                        .HasColumnType("integer");

                    b.Property<string>("StudyLanguage")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HighSchool");
                });

            modelBuilder.Entity("iknow_api.Models.Major", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PIT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SIIS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SEIS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "KN"
                        });
                });

            modelBuilder.Entity("iknow_api.Models.MajorSubjects", b =>
                {
                    b.Property<int>("MajorId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Accreditation")
                        .HasColumnType("integer");

                    b.Property<int>("MandatorySemester")
                        .HasColumnType("integer");

                    b.HasKey("MajorId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("MajorSubjects");
                });

            modelBuilder.Entity("iknow_api.Models.PassedSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePassed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<int>("SemesterSubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SemesterSubjectId")
                        .IsUnique();

                    b.ToTable("PassedSubjects");
                });

            modelBuilder.Entity("iknow_api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("iknow_api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("iknow_api.Models.SemesterSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrolledSemesterId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<bool>("Signature")
                        .HasColumnType("boolean");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnrolledSemesterId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("SemesterSubjects");
                });

            modelBuilder.Entity("iknow_api.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwardedCredits")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int?>("DependencyCredit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("iknow_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Bday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Citizenship")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EMBG")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Index")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("iknow_api.Models.UserDocuments", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("UserDocuments");
                });

            modelBuilder.Entity("iknow_api.Models.ContactInfo", b =>
                {
                    b.HasOne("iknow_api.Models.User", "User")
                        .WithOne("ContactInfo")
                        .HasForeignKey("iknow_api.Models.ContactInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("iknow_api.Models.DependencySubject", b =>
                {
                    b.HasOne("iknow_api.Models.Subject", "Dependency")
                        .WithMany("Dependents")
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("iknow_api.Models.Subject", "Subject")
                        .WithMany("Dependencies")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dependency");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("iknow_api.Models.EnrolledSemesters", b =>
                {
                    b.HasOne("iknow_api.Models.ActiveSemesters", "Semester")
                        .WithMany("EnrolledSemesters")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("iknow_api.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iknow_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Semester");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iknow_api.Models.EnrollmentInfo", b =>
                {
                    b.HasOne("iknow_api.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iknow_api.Models.User", "User")
                        .WithOne("EnrollmentInfo")
                        .HasForeignKey("iknow_api.Models.EnrollmentInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iknow_api.Models.HighSchool", b =>
                {
                    b.HasOne("iknow_api.Models.User", "User")
                        .WithOne("HighSchool")
                        .HasForeignKey("iknow_api.Models.HighSchool", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("iknow_api.Models.MajorSubjects", b =>
                {
                    b.HasOne("iknow_api.Models.Major", "Majors")
                        .WithMany("Subjects")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iknow_api.Models.Subject", "Subjects")
                        .WithMany("Majors")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Majors");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("iknow_api.Models.PassedSubject", b =>
                {
                    b.HasOne("iknow_api.Models.SemesterSubject", "SemesterSubject")
                        .WithOne("PassedSubject")
                        .HasForeignKey("iknow_api.Models.PassedSubject", "SemesterSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SemesterSubject");
                });

            modelBuilder.Entity("iknow_api.Models.Payment", b =>
                {
                    b.HasOne("iknow_api.Models.EnrolledSemesters", "EnrolledSemesters")
                        .WithMany("Users")
                        .HasForeignKey("EnrollmentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iknow_api.Models.User", "User")
                        .WithMany("EnrolledSemesters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnrolledSemesters");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iknow_api.Models.RefreshToken", b =>
                {
                    b.HasOne("iknow_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("iknow_api.Models.SemesterSubject", b =>
                {
                    b.HasOne("iknow_api.Models.EnrolledSemesters", "EnrolledSemester")
                        .WithMany("SemesterSubjects")
                        .HasForeignKey("EnrolledSemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("iknow_api.Models.User", "Professor")
                        .WithMany("TeachingSubjects")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("iknow_api.Models.Subject", "Subject")
                        .WithMany("SemesterSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("iknow_api.Models.User", "User")
                        .WithMany("EnrolledSemesterUserSubjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnrolledSemester");

                    b.Navigation("Professor");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iknow_api.Models.UserDocuments", b =>
                {
                    b.HasOne("iknow_api.Models.Documents", "Documents")
                        .WithMany("User")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iknow_api.Models.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documents");

                    b.Navigation("User");
                });

            modelBuilder.Entity("iknow_api.Models.ActiveSemesters", b =>
                {
                    b.Navigation("EnrolledSemesters");
                });

            modelBuilder.Entity("iknow_api.Models.Documents", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("iknow_api.Models.EnrolledSemesters", b =>
                {
                    b.Navigation("SemesterSubjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("iknow_api.Models.Major", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("iknow_api.Models.SemesterSubject", b =>
                {
                    b.Navigation("PassedSubject");
                });

            modelBuilder.Entity("iknow_api.Models.Subject", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");

                    b.Navigation("Majors");

                    b.Navigation("SemesterSubjects");
                });

            modelBuilder.Entity("iknow_api.Models.User", b =>
                {
                    b.Navigation("ContactInfo");

                    b.Navigation("Documents");

                    b.Navigation("EnrolledSemesterUserSubjects");

                    b.Navigation("EnrolledSemesters");

                    b.Navigation("EnrollmentInfo");

                    b.Navigation("HighSchool");

                    b.Navigation("TeachingSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
